export const el = {
  appShell: document.getElementById("app-shell"),
  sidebar: document.getElementById("sidebar"),
  scrim: document.getElementById("scrim"),
  openSidebar: document.getElementById("open-sidebar"),
  closeSidebar: document.getElementById("close-sidebar"),
  notebook: document.getElementById("notebook"),
  pageHeader: document.getElementById("page-header"),
  pageBody: document.getElementById("page-body"),
  pageList: document.getElementById("page-list"),
  pageSearch: document.getElementById("page-search"),
  searchEmpty: document.getElementById("search-empty"),
  pageListLabel: document.getElementById("page-list-label"),
  modeBreadcrumb: document.getElementById("mode-breadcrumb"),
  topbar: document.querySelector(".topbar"),
  miniPlayer: document.getElementById("mini-player"),
  miniPlay: document.getElementById("mini-play"),
  modeList: document.getElementById("mode-list"),
  form: document.getElementById("composer"),
  field: document.getElementById("field"),
  line: document.getElementById("line"),
  send: document.getElementById("send"),
  hint: document.getElementById("hint"),
  chips: document.getElementById("composer-chips"),
  idleNudge: document.getElementById("idle-nudge"),
  idleRemember: document.getElementById("idle-remember"),
  idleDismiss: document.getElementById("idle-dismiss"),
};
